image: node:latest

stages:
  - test
  - deploy
  - teardown

variables:
  AWS_REGION: us-east-2
before_script:
  - npm install -g serverless
  - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
  - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
  - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1


##########
#  JOBS  #
##########

unit tests:
  stage: test
  variables:
    DBHOST: $DBHOST_DEV
  script:
    - echo $DBHOST


deploy dev:
  stage: deploy
  when: manual
  environment:
    name: develop
    url: "https://${AWS_REGION}.console.aws.amazon.com/lambda/home?region=${AWS_REGION}#/applications/todolist-dev"
    on_stop: teardown dev
  script:
    - npm install --production
    - serverless deploy --stage dev --region $AWS_REGION --verbose
  only:
    - develop
    

teardown dev:
  stage: teardown
  when: manual
  environment:
    name: develop
    action: stop
  script:
    - npm install --production
    - serverless remove --stage dev --region $AWS_REGION --verbose


deploy production:
  stage: deploy
  environment:
    name: production
    url: "https://${AWS_REGION}.console.aws.amazon.com/lambda/home?region=${AWS_REGION}#/applications/todolist-production"
  script:
    - npm install --production
    - serverless deploy --stage production --region $AWS_REGION --verbose
  only:
    - master
