service: todolist

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  apiName: todolist
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"
  vpc:
    securityGroupIds:
      - sg-07df6ee81bd0b35d4
    subnetIds:
      - subnet-10a51476
      - subnet-122b9749
      - subnet-03b6014a
  environment:
    SECRET: 12345
    DBDIALECT: postgres
    DBHOST: todolist.cdyqppsniqqs.sa-east-1.rds.amazonaws.com
    DBUSER: postgres
    DBPASSWORD: postgres
    DBDATABASE: todolist
    DBPORT: 5432


functions: ${file(serverless-dynamic.js)}

