  authenticationUser:
    handler: modules/users/endpoints/auth.login
    events:
      - http:
          method: POST
          path: api/user/login
          cors: true
  
  createUser:
    handler: modules/users/endpoints/create.create
    events:
      - http:
          method: POST
          path: api/user/
          cors: true

  getUser:
    handler: modules/users/endpoints/read.get
    events:
      - http:
          method: GET
          path: api/user/
          cors: true
  
  syncDb:
    handler: modules/users/endpoints/read.sync
    events:
      - http:
          method: GET
          path: api/sync/
          cors: true